### ISSUE TITLE
subprocess encoding error

### ISSUE THREAD

**Issue by sergej3** [M-y/auto-brightness#2]
I tried the new version today and it's still not starting the application. Here's the output:

C:\Users\Alexander\Downloads\autobrightness_1.6.2-windows_debug>autobrightness.exe
Traceback (most recent call last):
  File "autobrightness\__main__.py", line 79, in <module>
  File "autobrightness\__main__.py", line 74, in main
  File "autobrightness\gui\trayicon.py", line 17, in __init__
  File "autobrightness\gui\daemon.py", line 24, in start
  File "subprocess.py", line 782, in __init__
LookupError: unknown encoding: cp850.
[2448] Failed to execute script __main__

Hope it helps

**Comment by M-y** [comment]
Could you try [1.6.3_alpha](https://github.com/M-y/auto-brightness/releases/tag/1.6.3_alpha)

**Comment by sergej3** [comment]
will do and report back. thank you for your help!

Muhammed YILDIRIM <notifications@github.com> schrieb am Do., 1. Okt. 2020,
18:28:

**Comment by sergej3** [comment]
C:\Users\Sergej\Downloads\autobrightness_1.6.3_alpha-windows_debug>autobrightness.exe
Traceback (most recent call last):
  File "autobrightness\__main__.py", line 79, in <module>
  File "autobrightness\__main__.py", line 74, in main
  File "autobrightness\gui\trayicon.py", line 17, in __init__
  File "autobrightness\gui\daemon.py", line 24, in start
  File "subprocess.py", line 782, in __init__
LookupError: unknown encoding: cp65001.
[9596] Failed to execute script __main__

hey there, above the current error message from cmd line, unfortunately
it's still not working



Am Do., 1. Okt. 2020 um 18:43 Uhr schrieb Sergej Schmal <
sergej.schmal1@gmail.com>:

**Comment by phmikas** [comment]
Same problem after some seconds when started autobrightness.exe on Windows 10 (even as admin): "Failed to execute script __main__"!
